SET SERVEROUTPUT ON;
DECLARE 
    
--    COD_S VARCHAR2(5);
--    NOM_L VARCHAR2(30);
--    COD_L VARCHAR2(5);
    
BEGIN


    --MOSTRAR LIBROS
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('------INFORMACIONES SOBRE LIBROS-------');
        MOSTRAR_LIBROS;
        
        
        
    --PRESTAR 5 LIBROS USANDO PROCEDURE PRESTAR(NOMBRE_LIBRO, CODIGO_SOCIO);
        PRESTAR('LIBRO_2', 'ABC12');
        PRESTAR('LIBRO_2', 'DEF34');
        PRESTAR('LIBRO_1', 'ABC12');
        PRESTAR('LIBRO_3', 'JKL78');
        PRESTAR('LIBRO_1', 'GHI56');
    
    
    
    
    --DEVOLVER TRES LIBROS USANDO PROCEDURE DEVOLVER(CODIGO_LIBRO)
        DEVOLVER('2345A');
        DEVOLVER('2345B');
        DEVOLVER('1234A');
    
    
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('--------- INFORMACIONES DESPUES DE DEVOLVER 3 LIBROS  --------- ');
    
    
        --MOSTRAR SOCIOS
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('------INFORMACIONES SOBRE SOCIOS-------');
        MOSTRAR_SOCIOS;
        
        --MOSTRAR PRESTAS 
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('------TODOS LOS OPERACIONES------ ');
        MOSTRAR_OPERACIONES;
        
        --MOSTRAR EL TOTAL Y MEDIA DE MULTAS
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('TOTAL DE MULTAS:' || TOTAL_MULTA('TOTAL'));
        
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('MEDIA DE MULTAS:' || TOTAL_MULTA('MEDIA'));
    
    
    
    --DEVOLVER TODOS LOS LIBROS QUE QUEDAN USANDO LA PROCEDURE DEVOLVER_TODO()
        DEVOLVER_TODO;
    

END;
/



SELECT * FROM SOCIOS;
SELECT * FROM LIBROS;
SELECT * FROM PRESTAS;
EXEC MOSTRAR_OPERACIONES;